VERSION = '2026-10-06-v1'
TITLE = 'Dashvanti Driver Partner Agreement & Terms of Service'
STATEMENT = 'By typing my full name and clicking Accept & Continue, I confirm that I have read, understood, and agreed to the Dashvanti Driver Partner Agreement and Terms of Service.'
SUCCESS = 'Thank you. Your acceptance of the Dashvanti Driver Partner Agreement has been recorded. Please continue with account registration.'

ACKNOWLEDGEMENTS = [
    ('platform', 'I understand that Dashvanti is a technology platform only.'),
    ('independent_contractor', 'I understand that I am an Independent Contractor and not an employee of Dashvanti.'),
    ('employment_benefits', 'I understand that Dashvanti does not provide employment benefits.'),
    ('vehicle_insurance', 'I understand that Dashvanti does not provide vehicle insurance.'),
    ('health_insurance', 'I understand that Dashvanti does not provide health insurance.'),
    ('accident_insurance', 'I understand that Dashvanti does not provide accident insurance.'),
    ('hospitalization', 'I understand that Dashvanti does not provide hospitalization benefits.'),
    ('disability', 'I understand that Dashvanti does not provide disability benefits.'),
    ('life_insurance', 'I understand that Dashvanti does not provide life insurance.'),
    ('death_benefits', 'I understand that Dashvanti does not provide death benefits.'),
    ('financial_assistance', 'I understand that Dashvanti does not provide financial assistance to me or my family in case of injury, accident, disability, hospitalization, or death.'),
    ('legal_documents', 'I understand that I am solely responsible for maintaining valid licenses, permits, registrations, and insurance required by law.'),
    ('safety', 'I agree that I am fully responsible for my own safety while performing deliveries.'),
    ('own_risk', 'I understand that I perform delivery services entirely at my own risk.'),
    ('policies', 'I agree to follow all Dashvanti Driver Policies, Terms & Conditions, and Community Guidelines.'),
    ('accurate_information', 'I certify that all information and documents submitted to Dashvanti are true and accurate.'),
    ('agreement', 'I agree to the Dashvanti Driver Partner Agreement and Terms of Service.'),
]

SECTIONS = [
    ('1. Parties and acceptance', 'This agreement is between Dashvanti, the operator of the Dashvanti Food Delivery Platform, and the individual driver partner identified by the full legal name entered below. It governs your application, use of the driver portal and performance of deliveries arranged through the platform. Read the complete agreement before accepting. If you do not agree, decline and do not register or use driver onboarding.'),
    ('2. Technology platform and independent services', 'Dashvanti provides technology that connects customers, restaurants and independent delivery partners. You provide delivery services as an independent contractor, not as an employee of Dashvanti. Subject to applicable law and accepted delivery commitments, you choose when to make yourself available and whether to accept an offered delivery. Registration does not guarantee approval, orders, earnings, continued platform access or employment.'),
    ('3. No employment benefits', 'Dashvanti does not provide employment benefits, paid leave, retirement benefits or employee compensation through this agreement. You are responsible for your own operating expenses and for taxes and other obligations applicable to your independent delivery services. The descriptions in this agreement do not override any employment classification, statutory benefit or obligation imposed by applicable law.'),
    ('4. No platform-provided insurance or financial assistance', 'Dashvanti does not provide vehicle, health, accident or life insurance; hospitalization, disability or death benefits; or financial assistance to you or your family in the event of injury, accident, disability, hospitalization or death. A nominee entry, uploaded insurance document, SOS feature or administrative insurance record is not insurance coverage and does not create a promise to pay benefits. Obtain and maintain any insurance required by law and any additional coverage you consider appropriate at your own expense.'),
    ('5. Eligibility, documents and vehicle compliance', 'You must be legally eligible to perform deliveries and maintain valid driving licences, permits, vehicle registrations and insurance required by the laws that apply where you operate. Use a roadworthy vehicle authorised for the intended delivery activity. Submit only true, current and accurate identity, vehicle, bank and other requested information. Notify Dashvanti of material changes and renew expiring documents. Dashvanti may review or reject an application and request additional documents; submitting documents is not confirmation that your legal obligations have been satisfied.'),
    ('6. Safety and personal responsibility', 'You are responsible for your own safety while performing deliveries and perform delivery services at your own risk, subject to rights and responsibilities that cannot lawfully be excluded. Follow traffic rules, signals, speed limits and parking restrictions; use required protective equipment; and never drive while impaired or distracted. Stop safely before interacting with the app. Navigation, ETA and route suggestions are advisory and may be inaccurate. Do not follow an unsafe or unlawful instruction. Do not enter an unsafe location or continue an unsafe delivery; contact support when appropriate.'),
    ('7. Delivery standards and community conduct', 'Treat customers, restaurant staff, other partners and the public respectfully. Do not harass, discriminate, threaten or misuse customer information. Handle orders hygienically, preserve packaging and follow lawful pickup and delivery instructions. Provide accurate status updates and complete the required pickup or delivery verification. Do not falsify GPS, documents, deliveries, payments or ratings. Notify support of delays, cancellations, missing items and other delivery problems. Follow the Driver Policies and Community Guidelines communicated to you; material changes requiring new agreement will be presented for acceptance.'),
    ('8. Earnings, fees and refundable deposit', 'Review the delivery offer and applicable earnings before accepting it. Earnings, adjustments, payment status and withdrawal records are available in the driver portal. Do not assume an estimated amount is a guaranteed net income. Where applicable, onboarding requires a refundable deposit of INR 1,000 for a bike or scooter or INR 3,000 for a car. Deposit payment alone does not approve or activate your account. Refunds require validation of the recorded payment and applicable account and order conditions; any adjustment or refusal must be explained through support and remain subject to applicable law. Sandbox payments are test transactions and do not activate live delivery access.'),
    ('9. Location, information and privacy', 'To provide dispatch, navigation, delivery tracking, verification and safety features, Dashvanti processes your account and submitted document information and, when delivery tracking is enabled, live location and necessary delivery milestones. Relevant delivery status and location may be shared with the customer, restaurant and authorised operations staff. Keep your credentials private. Your agreement version, typed legal name, acknowledgements, acceptance time, IP address and browser and device information are recorded as consent evidence. Access to private documents is restricted. Contact support for privacy questions and requests.'),
    ('10. Incidents and emergencies', 'If an emergency occurs, contact the appropriate local emergency services first and stop in a safe place. The SOS feature records an incident and attempts to notify support and configured contacts; it is not an emergency response guarantee, an insurance policy or a commitment to financial assistance. Report incidents accurately and provide information needed to investigate them.'),
    ('11. Review, restriction and termination', 'Dashvanti may request additional verification, issue warnings or restrict, suspend or deactivate access for inaccurate documents, fraud, unsafe conduct, policy violations or other legitimate platform safety and operational reasons. You may stop using the platform, subject to completing or properly cancelling accepted deliveries and resolving outstanding payment matters. Contact support to ask for the reason for an action or to dispute a decision. These provisions do not remove legal rights or earned amounts that remain payable.'),
    ('12. Liability and rights preserved by law', 'Nothing in this agreement excludes liability that cannot legally be excluded, excuses unlawful conduct, waives mandatory statutory rights or prevents a lawful complaint or claim. Independent contractor wording does not determine legal status where applicable law provides otherwise. The safety and risk acknowledgements do not release Dashvanti from obligations or liability that applicable law imposes. If a provision is unenforceable, the remaining lawful provisions continue to apply.'),
    ('13. Changes, support and electronic consent', 'A new material agreement version will require a fresh acceptance before driver onboarding can continue. Your typed full legal name and explicit acknowledgement choices record your electronic agreement to the version shown on this screen. You may decline before account registration. For agreement, onboarding, payment or safety questions, contact support@dashvanti.com, +1 615 478 6018 or +91 90968 96318. By accepting, you confirm that you have read and understood this agreement and that the information you subsequently submit will be true and accurate.'),
]
