
CREATE TABLE event_outbox (
	event_id VARCHAR2(36 CHAR) NOT NULL, 
	event_type VARCHAR2(60 CHAR) NOT NULL, 
	payload CLOB NOT NULL, 
	published SMALLINT NOT NULL, 
	created_at DATE NOT NULL, 
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	PRIMARY KEY (id), 
	UNIQUE (event_id)
)

;
CREATE INDEX ix_event_outbox_published ON event_outbox (published);

CREATE TABLE system_config (
	key VARCHAR2(100 CHAR) NOT NULL, 
	value VARCHAR2(2000 CHAR) NOT NULL, 
	PRIMARY KEY (key)
)

;

CREATE TABLE users (
	email VARCHAR2(254 CHAR) NOT NULL, 
	password VARCHAR2(255 CHAR) NOT NULL, 
	role VARCHAR2(20 CHAR) NOT NULL, 
	name VARCHAR2(120 CHAR) NOT NULL, 
	phone VARCHAR2(30 CHAR), 
	token_version INTEGER NOT NULL, 
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	PRIMARY KEY (id), 
	UNIQUE (email)
)

;

CREATE TABLE customers (
	id INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(id) REFERENCES users (id)
)

;

CREATE TABLE drivers (
	id INTEGER NOT NULL, 
	is_online SMALLINT NOT NULL, 
	vehicle_type VARCHAR2(80 CHAR), 
	vehicle_number VARCHAR2(80 CHAR), 
	PRIMARY KEY (id), 
	FOREIGN KEY(id) REFERENCES users (id)
)

;

CREATE TABLE files (
	user_id INTEGER NOT NULL, 
	purpose VARCHAR2(30 CHAR) NOT NULL, 
	entity_id INTEGER, 
	path VARCHAR2(1000 CHAR) NOT NULL, 
	mime VARCHAR2(80 CHAR) NOT NULL, 
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id)
)

;

CREATE TABLE password_resets (
	user_id INTEGER NOT NULL, 
	digest VARCHAR2(64 CHAR) NOT NULL, 
	expires_at DATE NOT NULL, 
	used SMALLINT NOT NULL, 
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id), 
	UNIQUE (digest)
)

;

CREATE TABLE restaurants (
	id INTEGER NOT NULL, 
	name VARCHAR2(120 CHAR) NOT NULL, 
	description VARCHAR2(1000 CHAR), 
	cuisine VARCHAR2(80 CHAR) NOT NULL, 
	kind VARCHAR2(20 CHAR) NOT NULL, 
	address VARCHAR2(500 CHAR), 
	is_open SMALLINT NOT NULL, 
	opening VARCHAR2(5 CHAR) NOT NULL, 
	closing VARCHAR2(5 CHAR) NOT NULL, 
	delivery_minutes INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(id) REFERENCES users (id)
)

;

CREATE TABLE addresses (
	customer_id INTEGER NOT NULL, 
	label VARCHAR2(80 CHAR) NOT NULL, 
	details VARCHAR2(500 CHAR) NOT NULL, 
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	PRIMARY KEY (id), 
	FOREIGN KEY(customer_id) REFERENCES customers (id)
)

;
CREATE INDEX ix_addresses_customer_id ON addresses (customer_id);

CREATE TABLE menu_items (
	restaurant_id INTEGER NOT NULL, 
	name VARCHAR2(120 CHAR) NOT NULL, 
	description VARCHAR2(1000 CHAR), 
	category VARCHAR2(80 CHAR), 
	price NUMERIC(12, 2) NOT NULL, 
	veg SMALLINT NOT NULL, 
	available SMALLINT NOT NULL, 
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	PRIMARY KEY (id), 
	FOREIGN KEY(restaurant_id) REFERENCES restaurants (id)
)

;
CREATE INDEX ix_menu_items_restaurant_id ON menu_items (restaurant_id);

CREATE TABLE orders (
	customer_id INTEGER NOT NULL, 
	restaurant_id INTEGER NOT NULL, 
	driver_id INTEGER, 
	request_key VARCHAR2(64 CHAR) NOT NULL, 
	status VARCHAR2(40 CHAR) NOT NULL, 
	"mode" VARCHAR2(20 CHAR) NOT NULL, 
	address VARCHAR2(500 CHAR) NOT NULL, 
	total NUMERIC(12, 2) NOT NULL, 
	delivery_fee NUMERIC(12, 2) NOT NULL, 
	created_at DATE NOT NULL, 
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	PRIMARY KEY (id), 
	UNIQUE (customer_id, request_key), 
	FOREIGN KEY(customer_id) REFERENCES customers (id), 
	FOREIGN KEY(restaurant_id) REFERENCES restaurants (id), 
	FOREIGN KEY(driver_id) REFERENCES drivers (id)
)

;
CREATE INDEX ix_orders_restaurant_id ON orders (restaurant_id);
CREATE INDEX ix_orders_customer_id ON orders (customer_id);
CREATE INDEX ix_orders_driver_id ON orders (driver_id);

CREATE TABLE cart_items (
	customer_id INTEGER NOT NULL, 
	menu_item_id INTEGER NOT NULL, 
	quantity INTEGER NOT NULL, 
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	PRIMARY KEY (id), 
	UNIQUE (customer_id, menu_item_id), 
	FOREIGN KEY(customer_id) REFERENCES customers (id), 
	FOREIGN KEY(menu_item_id) REFERENCES menu_items (id)
)

;

CREATE TABLE delivery_status (
	order_id INTEGER NOT NULL, 
	status VARCHAR2(40 CHAR) NOT NULL, 
	created_at DATE NOT NULL, 
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	PRIMARY KEY (id), 
	FOREIGN KEY(order_id) REFERENCES orders (id)
)

;
CREATE INDEX ix_delivery_status_order_id ON delivery_status (order_id);

CREATE TABLE order_items (
	order_id INTEGER NOT NULL, 
	menu_item_id INTEGER NOT NULL, 
	name VARCHAR2(120 CHAR) NOT NULL, 
	quantity INTEGER NOT NULL, 
	price NUMERIC(12, 2) NOT NULL, 
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	PRIMARY KEY (id), 
	FOREIGN KEY(order_id) REFERENCES orders (id), 
	FOREIGN KEY(menu_item_id) REFERENCES menu_items (id)
)

;
CREATE INDEX ix_order_items_order_id ON order_items (order_id);

CREATE TABLE ratings (
	order_id INTEGER NOT NULL, 
	restaurant INTEGER NOT NULL, 
	driver INTEGER, 
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	PRIMARY KEY (id), 
	UNIQUE (order_id), 
	FOREIGN KEY(order_id) REFERENCES orders (id)
)

;

CREATE TABLE reviews (
	order_id INTEGER NOT NULL, 
	customer_id INTEGER NOT NULL, 
	text VARCHAR2(2000 CHAR) NOT NULL, 
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	PRIMARY KEY (id), 
	UNIQUE (order_id), 
	FOREIGN KEY(order_id) REFERENCES orders (id), 
	FOREIGN KEY(customer_id) REFERENCES customers (id)
)

;
