from django.urls import path
from common_app import views as common
from . import views

urlpatterns = [
    path('order/<int:order_id>/cancellation', common.cancellation),
    path('restaurant/<int:entity_id>/order-availability', views.order_availability, {'entity':'restaurant'}),
    path('menu/<int:entity_id>/order-availability', views.order_availability, {'entity':'menu'}),
    path('order/<int:order_id>/tracking', common.tracking),
    path('order-sound', common.order_sound),
    path('route-distance', common.route_distance),
    path('notification-panel', views.notification_panel),
    path('address-book', views.address_book),
    path('order/<int:order_id>/bill', common.download_report),
    path('live-alerts', common.live_alerts),
    path('checkout/eta', views.checkout_eta),
    path('login',common.auth,{'role':'customer','action':'login'}),
    path('register',common.auth,{'role':'customer','action':'register'}),
    path('forgot',common.auth,{'role':'customer','action':'forgot'}),
    path('reset',common.auth,{'role':'customer','action':'reset'}),
    path('logout',common.logout,{'role':'customer'}),
    path('profile',common.profile),
    path('files',common.files),
    path('files/<int:file_id>',common.download),
    path('orders',views.orders),
    path('order/<int:order_id>',views.order),
    path('restaurants',views.restaurants),
    path('search-suggestions',views.search_suggestions),
    path('order-mode',views.order_mode),
    path('photo',views.photo),
    path('location',views.location),
    path('restaurant/<int:restaurant_id>',views.restaurant),
    path('cart',views.cart),
    path('checkout',views.checkout),
    path('checkout/quote',views.checkout_quote),
    path('addresses',views.addresses),
    path('addresses/<int:address_id>',views.addresses),
    path('order/<int:order_id>/track',views.order),
    path('order/<int:order_id>/reorder',views.reorder),
    path('order/<int:order_id>/review',views.review),
    path('support',common.support),
    path('notifications',common.notifications),
    path('order/<int:order_id>/chat',common.chat),
]
