from django import forms


class PartnerForm(forms.Form):
    first_name = forms.CharField(max_length=80)
    last_name = forms.CharField(max_length=80)
    mobile = forms.CharField(label='Mobile number (+91)', max_length=20)
    email = forms.EmailField()
    date_of_birth = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    gender = forms.ChoiceField(choices=[('Female','Female'),('Male','Male'),('Other','Other'),('Prefer not to say','Prefer not to say')])
    address = forms.CharField(widget=forms.Textarea(attrs={'rows': 2}), max_length=500)
    aadhaar = forms.RegexField(r'^[2-9][0-9]{11}$', widget=forms.PasswordInput(render_value=False), label='Aadhaar number (used for duplicate checks; only last four digits retained)')
    pan = forms.RegexField(r'^[A-Z]{5}[0-9]{4}[A-Z]$')
    license_number = forms.CharField(max_length=40)
    vehicle_type = forms.ChoiceField(choices=[(v,v) for v in ['Bike','Scooter','Car']])
    vehicle_number = forms.CharField(max_length=30)
    account_holder = forms.CharField(max_length=120)
    account_number = forms.RegexField(r'^\d{9,18}$', widget=forms.PasswordInput(render_value=False))
    ifsc = forms.RegexField(r'^[A-Z]{4}0[A-Z0-9]{6}$')
    upi = forms.CharField(required=False, max_length=120)
    emergency_name = forms.CharField(max_length=120)
    emergency_relationship = forms.CharField(max_length=40)
    emergency_phone = forms.CharField(max_length=20)
    nominee_name = forms.CharField(max_length=120)
    nominee_relationship = forms.CharField(max_length=40)
    nominee_phone = forms.CharField(max_length=20)
    terms = forms.BooleanField(label='I agree to the Terms & Conditions')
    driver_policy = forms.BooleanField(label='I agree to the Driver Policy')
    insurance_policy = forms.BooleanField(label='I accept the Insurance Policy and understand coverage requires an active issued policy')
    identity_consent = forms.BooleanField(label='I consent to private identity-document processing for driver onboarding')
