ALTER TABLE orders ADD (payment_mode VARCHAR2(40 CHAR) DEFAULT 'Card');

CREATE TABLE payout_transactions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id),
  payee_role VARCHAR2(20 CHAR) NOT NULL,
  payee_id INTEGER NOT NULL,
  amount NUMBER(12,2) DEFAULT 0 NOT NULL,
  status VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
  method VARCHAR2(30 CHAR) DEFAULT 'QUICK_PAY' NOT NULL,
  reference VARCHAR2(80 CHAR) UNIQUE NOT NULL,
  created_at DATE NOT NULL,
  paid_at DATE
);

CREATE INDEX ix_payout_transactions_order_id ON payout_transactions(order_id);
CREATE INDEX ix_payout_transactions_payee_role ON payout_transactions(payee_role);
CREATE INDEX ix_payout_transactions_payee_id ON payout_transactions(payee_id);
CREATE INDEX ix_payout_transactions_status ON payout_transactions(status);
