-- PostgreSQL Application Schema: DASHVANTI
-- Migrated from Oracle SQL DDL
-- Compatible with PostgreSQL 12+

-- Drop tables if re-initialization is needed (in dependency order)
DROP TABLE IF EXISTS payout_transactions CASCADE;
DROP TABLE IF EXISTS delivery_status CASCADE;
DROP TABLE IF EXISTS order_messages CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS cart_items CASCADE;
DROP TABLE IF EXISTS menu_items CASCADE;
DROP TABLE IF EXISTS customer_locations CASCADE;
DROP TABLE IF EXISTS driver_locations CASCADE;
DROP TABLE IF EXISTS addresses CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS ratings CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS support_tickets CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS restaurant_presentations CASCADE;
DROP TABLE IF EXISTS platform_content CASCADE;
DROP TABLE IF EXISTS files CASCADE;
DROP TABLE IF EXISTS password_resets CASCADE;
DROP TABLE IF EXISTS audit_events CASCADE;
DROP TABLE IF EXISTS event_outbox CASCADE;
DROP TABLE IF EXISTS promotions CASCADE;
DROP TABLE IF EXISTS system_config CASCADE;
DROP TABLE IF EXISTS drivers CASCADE;
DROP TABLE IF EXISTS restaurants CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 1. USERS
CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    name VARCHAR(120) NOT NULL,
    phone VARCHAR(30),
    token_version INTEGER NOT NULL DEFAULT 0,
    order_sound_enabled BOOLEAN DEFAULT FALSE
);

-- 2. CUSTOMERS
CREATE TABLE customers (
    id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    order_mode VARCHAR(20) DEFAULT 'delivery'
);

-- 3. RESTAURANTS
CREATE TABLE restaurants (
    id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(120) NOT NULL,
    cuisine VARCHAR(80) NOT NULL,
    kind VARCHAR(20) NOT NULL,
    address VARCHAR(500),
    is_open BOOLEAN NOT NULL DEFAULT FALSE,
    opening VARCHAR(5) NOT NULL,
    closing VARCHAR(5) NOT NULL,
    delivery_minutes INTEGER NOT NULL,
    description VARCHAR(1000) DEFAULT ''
);

-- 4. DRIVERS
CREATE TABLE drivers (
    id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    is_online BOOLEAN NOT NULL DEFAULT FALSE,
    vehicle_type VARCHAR(80) DEFAULT '',
    vehicle_number VARCHAR(80) DEFAULT ''
);

-- 5. ADDRESSES
CREATE TABLE addresses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    label VARCHAR(80) NOT NULL,
    details VARCHAR(500) NOT NULL,
    is_default BOOLEAN DEFAULT FALSE,
    place_id VARCHAR(255) DEFAULT NULL
);

-- 6. CUSTOMER_LOCATIONS
CREATE TABLE customer_locations (
    customer_id INTEGER PRIMARY KEY REFERENCES customers(id) ON DELETE CASCADE,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    address VARCHAR(500) DEFAULT NULL
);

-- 7. DRIVER_LOCATIONS
CREATE TABLE driver_locations (
    driver_id INTEGER PRIMARY KEY REFERENCES drivers(id) ON DELETE CASCADE,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    heading DOUBLE PRECISION,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 8. FILES
CREATE TABLE files (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    purpose VARCHAR(30) NOT NULL,
    entity_id INTEGER,
    path VARCHAR(1000) NOT NULL,
    mime VARCHAR(80) NOT NULL
);

-- 9. MENU_ITEMS
CREATE TABLE menu_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INTEGER NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(1000),
    price NUMERIC(12, 2) NOT NULL,
    veg BOOLEAN NOT NULL DEFAULT TRUE,
    available BOOLEAN NOT NULL DEFAULT TRUE,
    category VARCHAR(80) DEFAULT 'General'
);

-- 10. CART_ITEMS
CREATE TABLE cart_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    menu_item_id INTEGER NOT NULL REFERENCES menu_items(id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL,
    special_instructions VARCHAR(1000) DEFAULT NULL,
    CONSTRAINT uq_cart_items_customer_menu UNIQUE (customer_id, menu_item_id)
);

-- 11. ORDERS
CREATE TABLE orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES customers(id),
    restaurant_id INTEGER NOT NULL REFERENCES restaurants(id),
    driver_id INTEGER REFERENCES drivers(id),
    request_key VARCHAR(64) NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'PLACED',
    mode VARCHAR(20) NOT NULL,
    payment_mode VARCHAR(40) DEFAULT 'Card',
    address VARCHAR(500) NOT NULL,
    total NUMERIC(12, 2) NOT NULL,
    delivery_fee NUMERIC(12, 2) NOT NULL,
    discount NUMERIC(12, 2) DEFAULT 0,
    tax NUMERIC(12, 2) DEFAULT 0,
    service_fee NUMERIC(12, 2) DEFAULT 0,
    tip NUMERIC(12, 2) DEFAULT 0,
    customer_zip VARCHAR(10),
    subtotal NUMERIC(12, 2) DEFAULT 0 NOT NULL,
    item_tax_total NUMERIC(12, 2) DEFAULT 0 NOT NULL,
    delivery_tax NUMERIC(12, 2) DEFAULT 0 NOT NULL,
    platform_fee NUMERIC(12, 2) DEFAULT 0 NOT NULL,
    platform_tax NUMERIC(12, 2) DEFAULT 0 NOT NULL,
    grand_total NUMERIC(12, 2) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_orders_customer_request UNIQUE (customer_id, request_key)
);

-- 12. ORDER_ITEMS
CREATE TABLE order_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    menu_item_id INTEGER NOT NULL REFERENCES menu_items(id),
    name VARCHAR(120) NOT NULL,
    quantity INTEGER NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    special_instructions VARCHAR(1000) DEFAULT NULL
);

-- 13. ORDER_MESSAGES
CREATE TABLE order_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id),
    body TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 14. DELIVERY_STATUS
CREATE TABLE delivery_status (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    status VARCHAR(40) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 15. PAYOUT_TRANSACTIONS
CREATE TABLE payout_transactions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    payee_role VARCHAR(20) NOT NULL,
    payee_id INTEGER NOT NULL,
    amount NUMERIC(12, 2) DEFAULT 0 NOT NULL,
    status VARCHAR(20) DEFAULT 'PENDING' NOT NULL,
    method VARCHAR(30) DEFAULT 'QUICK_PAY' NOT NULL,
    reference VARCHAR(80) UNIQUE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    paid_at TIMESTAMP
);

-- 16. RATINGS
CREATE TABLE ratings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL UNIQUE REFERENCES orders(id) ON DELETE CASCADE,
    restaurant INTEGER NOT NULL,
    driver INTEGER
);

-- 17. REVIEWS
CREATE TABLE reviews (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL UNIQUE REFERENCES orders(id) ON DELETE CASCADE,
    customer_id INTEGER NOT NULL REFERENCES customers(id),
    text VARCHAR(2000) NOT NULL
);

-- 18. SUPPORT_TICKETS
CREATE TABLE support_tickets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    order_id INTEGER REFERENCES orders(id) ON DELETE SET NULL,
    subject VARCHAR(120) NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'open',
    resolution TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 19. NOTIFICATIONS
CREATE TABLE notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    order_id INTEGER REFERENCES orders(id) ON DELETE SET NULL,
    kind VARCHAR(40) NOT NULL,
    body VARCHAR(500) NOT NULL,
    read_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 20. PASSWORD_RESETS
CREATE TABLE password_resets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    digest VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE
);

-- 21. AUDIT_EVENTS
CREATE TABLE audit_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    action VARCHAR(80) NOT NULL,
    target VARCHAR(160) NOT NULL,
    details TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 22. EVENT_OUTBOX
CREATE TABLE event_outbox (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(36) NOT NULL UNIQUE,
    event_type VARCHAR(60) NOT NULL,
    payload TEXT NOT NULL,
    published BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 23. PLATFORM_CONTENT
CREATE TABLE platform_content (
    key VARCHAR(80) PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    media_file_id INTEGER REFERENCES files(id) ON DELETE SET NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 24. PROMOTIONS
CREATE TABLE promotions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    code VARCHAR(40) NOT NULL UNIQUE,
    percent INTEGER NOT NULL,
    minimum NUMERIC(12, 2) NOT NULL DEFAULT 0,
    cap NUMERIC(12, 2) NOT NULL DEFAULT 0,
    first_order_only BOOLEAN NOT NULL DEFAULT FALSE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    starts_at TIMESTAMP,
    ends_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 25. RESTAURANT_PRESENTATIONS
CREATE TABLE restaurant_presentations (
    restaurant_id INTEGER PRIMARY KEY REFERENCES restaurants(id) ON DELETE CASCADE,
    cover_file_id INTEGER REFERENCES files(id) ON DELETE SET NULL,
    logo_file_id INTEGER REFERENCES files(id) ON DELETE SET NULL,
    gallery_file_ids TEXT NOT NULL DEFAULT '[]',
    busy_mode VARCHAR(20) NOT NULL DEFAULT 'open',
    busy_until TIMESTAMP,
    prep_extra_minutes INTEGER NOT NULL DEFAULT 0,
    capacity INTEGER NOT NULL DEFAULT 20,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 26. SYSTEM_CONFIG
CREATE TABLE system_config (
    key VARCHAR(100) PRIMARY KEY,
    value VARCHAR(2000) NOT NULL
);

-- INDEXES
CREATE INDEX ix_addresses_customer_id ON addresses (customer_id);
CREATE INDEX ix_audit_events_actor_id ON audit_events (actor_id);
CREATE INDEX ix_delivery_status_order_id ON delivery_status (order_id);
CREATE INDEX ix_event_outbox_published ON event_outbox (published);
CREATE INDEX ix_menu_items_restaurant_id ON menu_items (restaurant_id);
CREATE INDEX ix_notifications_order_id ON notifications (order_id);
CREATE INDEX ix_notifications_user_id ON notifications (user_id);
CREATE INDEX ix_orders_customer_id ON orders (customer_id);
CREATE INDEX ix_orders_driver_id ON orders (driver_id);
CREATE INDEX ix_orders_restaurant_id ON orders (restaurant_id);
CREATE INDEX ix_order_items_order_id ON order_items (order_id);
CREATE INDEX ix_order_messages_order_id ON order_messages (order_id);
CREATE INDEX ix_order_messages_user_id ON order_messages (user_id);
CREATE INDEX ix_payout_transactions_order_id ON payout_transactions (order_id);
CREATE INDEX ix_payout_transactions_payee_role ON payout_transactions (payee_role);
CREATE INDEX ix_payout_transactions_payee_id ON payout_transactions (payee_id);
CREATE INDEX ix_payout_transactions_status ON payout_transactions (status);
CREATE INDEX ix_support_tickets_order_id ON support_tickets (order_id);
CREATE INDEX ix_support_tickets_user_id ON support_tickets (user_id);
